version: "3.9"
services:
  smartledger:
    build: ./30-services/smartledger-v3_1
    environment:
      - DATABASE_URL=
      - PORT=4000
      - ORIGIN=
      - LOG_LEVEL=info
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartledger
    ports:
      - "5432:5432"