services:
  # Map host 11435 → container 11434 to avoid the 11434 conflict on your host
  smartnet-pod:
    image: ghcr.io/soulschoolacademy/smartnet-pod-golden:latest
    container_name: smartnet-pod-golden
    ports: [ "11435:11434" ]
    restart: unless-stopped
    labels: [ "com.centurylinklabs.watchtower.enable=true" ]

  db:
    image: postgres:15
    container_name: smartmail-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartnet
    ports: [ "5433:5432" ]
    volumes: [ "dbdata:/var/lib/postgresql/data" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smartnet"]
      interval: 5s
      timeout: 3s
      retries: 20

  # ✅ FIXED: build context points to repo root (..), dockerfile at root
  smartmail-api:
    build:
      context: ..
      dockerfile: Dockerfile.smartmail
    image: ghcr.io/soulschoolacademy/smartmail-api:dev-local
    container_name: smartmail-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/smartnet
    ports: [ "8088:8088" ]
    restart: unless-stopped
    labels: [ "com.centurylinklabs.watchtower.enable=true" ]

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: --label-enable --interval 3600
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    restart: unless-stopped
    depends_on: [ smartnet-pod, smartmail-api ]

volumes:
  dbdata:
