# REPO: SoulSchoolAcademy/smartnet-pod-golden
# PATH: .github/workflows/docker-publish.yml
name: Build & Push (GHCR)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: smartnet-pod-golden

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Compute lowercase owner
        id: prep
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CRPAT }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          # If your Dockerfile is NOT at the repo root, uncomment and set:
          # file: ./path/to/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.prep.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ steps.prep.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

