# REPO: SoulSchoolAcademy/smartnet-pod-golden
# PATH: .github/workflows/ghcr-smoke.yml
name: GHCR Smoke Test
on: workflow_dispatch
jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CRPAT }}
      - name: Confirm login
        run: echo "Logged in to ghcr.io as $GITHUB_ACTOR ✅"
