name: smartledger-ci

on:
  push:
    paths:
      - '30-services/smartledger-v3_1/**'
      - '.github/workflows/smartledger-ci.yml'
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./30-services/smartledger-v3_1
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/smartledger-v3_1:latest
